### ISSUE TITLE
patiënten gegevens 

### ISSUE THREAD

**Issue by DanVijl** [halcwb/AfsprakenProgramma#17]
1.  Kan bij geboortedatum ook een knopje **nu**?

2. De tab doorloop is niet helemaal soepel, slaat geboortedatum over en als je door geboortedatum heengaat kom je op clear. 

3. Is het mogelijk om door opname datum en geboortedatum te gaan zonder tab?

**Comment by halcwb** [comment]
- Knopje nu toegevoegd.
- Tab volgorde aangepast
- Punt 3 is lastig en misschien ook niet handig?
