### ISSUE TITLE
gewicht in patientengegevens

### ISSUE THREAD

**Issue by DanVijl** [halcwb/AfsprakenProgramma#18]
Gewicht wordt afgerond in hele kilogrammen en niet geaccepteerd onder de 1 kg. Daarnaast is het gg in grammen en het gewicht in kg, lijkt mij verwarrend.

**Comment by halcwb** [comment]
1. Gewicht kan tot 0,4 kg worden ingevoerd, maar niet lager.
2. Gewicht wordt tot 3 cijfers afgerond achter de komma weergegeven.
3. In principe wordt het geboortegewicht verder niet gebruikt voor berekeningen en is de invoer gevalideerd voor verschil kg - gram. Ook is volgens mij het geboortegewicht veelal weergegeven als gram.
