### ISSUE TITLE
Dosering controle epiduraal

### ISSUE THREAD

**Issue by halcwb** [halcwb/AfsprakenProgramma#2]
Comentaar van Erik:

> 1.	Concentratie wordt op gewicht aan gepast en niet de ml/uur (om voldoende spreiding over de epiduraal ruimte te hebben). Dus ml/kg is niet de oplossing.
> Mogelijk wel om in kg categorieën maxima / minima te stellen;
> -	Epiduraal bupi/suf altijd met NaCl 0,9%
> -	< 6 kg: min stand 1.0 en max stand 2.0 ml/uur
> -	> 6 kg: min stand 2.0 en max stand 8.0 ml/uur

**Comment by ErikKoomen** [comment]
Als reeds gemeld zou ik kijken naar de kids < 6 kg: min stand 1.0 en max 4.0 (dus geen 2.0 als nu in het protocol staat). Order Maarten Mensink, anesthesioloog / pijnspecialist

**Comment by halcwb** [comment]
Is het aantal gebruikte ml van de oplossing niet een eenvoudig rekensommetje? Dat zou ik als controle/berekening ook nog kunnen toevoegen?

**Comment by ErikKoomen** [comment]
Het aantal ml's wordt bepaald door het aantal dermatomen je de pijn wil bestrijden en is dus erg afhankelijk van de grootte van de ingreep. Helaas dus geen rekensom.
De rekensom is in de oplossing die is namelijk het gewicht x lokaal anesthesticum aangevuld tot 48 ml en dan een pomp stand, dus elk gewicht levert een andere oplossing op en volume geeft spreiding van blok

**Comment by halcwb** [comment]
Duidelijk. Is het volume dan wel altijd 48 mL?

**Comment by halcwb** [comment]
Ok, controle op loopsnelheid is gelukt maar kan niet eenvoudig gewichts afhankelijk. Volume is nu wel goed geregeld. 

Dus standaard zet de epi op Sterkte 0 mL in stand volume en controle stand is 1 - 8 mL /uur nog even onafhankelijk van gewicht.

**Comment by halcwb** [comment]
Dosering controle epiduraal nu ingesteld op hoeveelheid epiduraal oplossing en loopsnelheid.
