### ISSUE TITLE
1x per 36 uur

### ISSUE THREAD

**Issue by DanVijl** [halcwb/AfsprakenProgramma#22]
Voor gentamicine gebruiken we ook nog 1x per 36 uur als regel

**Comment by halcwb** [comment]
1 x / 36 uur = 2 x / 3 dagen. Kan het laatste ook gebruiken, maar zo staat het niet in het Kinderformularium.

**Comment by halcwb** [comment]
Is dit OK?

**Comment by DanVijl** [comment]
2x per 3 dagen is ook prima. Geldt voor prematuren 32-37 weken bij gentamicine
