### ISSUE TITLE
voorschrijven van vloeistoffen en zouten

### ISSUE THREAD

**Issue by DanVijl** [halcwb/AfsprakenProgramma#25]
Het voorschrijven van vloeistoffen als NaCl 2,9% en natriumbicarbonaat biedt niet de mogelijkheden die op dit moment gebruikt worden. NaBic is bijvoorbeeld alleen in mg voor te schrijven, iets wat arts en vpk niet gewend zijn. Daarnaast kunnen de meeste mensen niet beredeneren hoeveel mg/ml in de verpakking zit als het er niet direct op staat. Vaak staat het wel in mmol op de verpakking. Ook weten velen niet dat 42 mg/ml hetzelfde is als 4,2%. 
Verder mis in wat suppletie zouten, K fosfaat, Ca Lactaat
Als laatste staan de baby druppels voor Vitamine K 30 ugr/druppel en D  (40IE/dr) er niet in, wellicht omdat dit eigenlijk geen geneesmiddelen zijn en ook niet als zodanig zijn geregistreerd.

**Comment by ErikKoomen** [comment]
De suppletie van elelctrolyten blijft lastig, vaak in % op de verpakking, maar als medicament zou het eigenlijk asl mg voor geschreven dienen te worden....oplossing?

**Comment by halcwb** [comment]
De eenheid waarin wordt gedoseerd is nu per medicament configureerbaar.
