### ISSUE TITLE
Gluc 5% voor continue Ped medicatie eruit?

### ISSUE THREAD

**Issue by halcwb** [halcwb/AfsprakenProgramma#28]
Moet de optie gluc 5% voor continue medicatie eruit?

**Comment by ErikKoomen** [comment]
Ja deze mag er definitief uit, er is geen medicament opgelost in 5%, dus 10% glu en NaCl 0,9 is afdoende als oplosmedium voor medicatie iom met de apotheek

**Comment by halcwb** [comment]
Hoi Erik,

Ik zou de mogelijkheid van glucose 5% niet helemaal de deur uit doen. Nu wordt toch al automatisch de glucose 10% gekozen. Dus het zal alleen in situaties met een te hoge glucose intake veranderd worden. Voor de gebruiker maakt het dus niet uit.

Groet -- Casper
